// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbiFreight.Analytics.Data;

#nullable disable

namespace OrbiFreight.Analytics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM566503 ")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<int>("IdCarga")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGA");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NIVEL_RISCO");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdCarga");

                    b.ToTable("ALERTA", "RM566503 ");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Carga", b =>
                {
                    b.Property<int>("IdCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarga"));

                    b.Property<int?>("IdRota")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdTipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdCarga");

                    b.HasIndex("IdRota");

                    b.HasIndex("IdTipo");

                    b.ToTable("CARGA", "RM566503 ");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Rota", b =>
                {
                    b.Property<int>("IdRota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ROTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRota"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINO");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEM");

                    b.HasKey("IdRota");

                    b.ToTable("ROTA", "RM566503 ");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.TipoCarga", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("IdTipo");

                    b.ToTable("TIPO_CARGA", "RM566503 ");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Alerta", b =>
                {
                    b.HasOne("OrbiFreight.Analytics.Models.Carga", "Carga")
                        .WithMany("Alertas")
                        .HasForeignKey("IdCarga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Carga", b =>
                {
                    b.HasOne("OrbiFreight.Analytics.Models.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("IdRota");

                    b.HasOne("OrbiFreight.Analytics.Models.TipoCarga", "TipoCarga")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");

                    b.Navigation("TipoCarga");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Carga", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
