// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbiFreight.Analytics.Data;

#nullable disable

namespace OrbiFreight.Analytics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM566503")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CargaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("carga_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nivel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CargaId");

                    b.ToTable("ALERTA", "RM566503");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Carga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("destino");

                    b.Property<long>("MotoristaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("motorista_id");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("origem");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("placa_veiculo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<double>("TempMax")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("temp_max");

                    b.Property<double>("TempMin")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("temp_min");

                    b.Property<long>("TipoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("tipo_id");

                    b.Property<double>("UmidadeMax")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("umidade_max");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("CARGA", "RM566503");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.SensorLeitura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CargaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("carga_id");

                    b.Property<DateTime>("DataHoraLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora_leitura");

                    b.Property<double>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("temperatura");

                    b.Property<double>("Umidade")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("umidade");

                    b.HasKey("Id");

                    b.HasIndex("CargaId");

                    b.ToTable("SENSOR_LEITURA", "RM566503");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.TipoCarga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<int>("PrazoMaxHoras")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("prazo_max_horas");

                    b.Property<double>("TempMax")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("temp_max");

                    b.Property<double>("TempMin")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("temp_min");

                    b.Property<double>("UmidadeMax")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("umidade_max");

                    b.HasKey("Id");

                    b.ToTable("TIPO_CARGA", "RM566503");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", "RM566503");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Alerta", b =>
                {
                    b.HasOne("OrbiFreight.Analytics.Models.Carga", "Carga")
                        .WithMany("Alertas")
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Carga", b =>
                {
                    b.HasOne("OrbiFreight.Analytics.Models.TipoCarga", "TipoCarga")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCarga");
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.SensorLeitura", b =>
                {
                    b.HasOne("OrbiFreight.Analytics.Models.Carga", "Carga")
                        .WithMany()
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OrbiFreight.Analytics.Models.CoordenadaGPS", "Coordenadas", b1 =>
                        {
                            b1.Property<long>("SensorLeituraId")
                                .HasColumnType("NUMBER(19)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("longitude");

                            b1.HasKey("SensorLeituraId");

                            b1.ToTable("SENSOR_LEITURA", "RM566503");

                            b1.WithOwner()
                                .HasForeignKey("SensorLeituraId");
                        });

                    b.Navigation("Carga");

                    b.Navigation("Coordenadas")
                        .IsRequired();
                });

            modelBuilder.Entity("OrbiFreight.Analytics.Models.Carga", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
